### ISSUE TITLE
Function does not do what its name implies

### ISSUE THREAD

**Issue by WorldofKerry** [Haxrox/Realeux-Triangle-Reference-Model#1]
https://github.com/Haxrox/Reuleux-Triangle-Reference-Model/blob/6d37f1467f4be737a011a718087850998d2c1407/main.py#L38

**Comment by Haxrox** [comment]
Fixed in https://github.com/Haxrox/Reuleaux-Triangle-Reference-Model/commit/3efaaaa2e9fdb2f617edf4232ee13ed270cba4ff
